---
- hosts: localhost
  gather-facts: no
  connection: local
  vars_files:
  - aws
vars:
  bucketname: asolankibucket
tasks:
 - name: Create a S3 bucket
   s3: 
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: "{{ bucketname }}"
    mode: create